### PR TITLE
added myself

### PR DESCRIPTION
**Pull request by PushkarAdhyapak**
added myself

### CODE REVIEW

**Comment by adicadi** [comment]
Well Done! Thanks for the contribution. 💖

**Comment by PushkarAdhyapak** [comment]
Thanks for merging.
Is this under Hacktoberfest 2021 ?

**Comment by adicadi** [comment]
Yes

**Comment by adicadi** [comment]
> Thanks for merging. Is this under Hacktoberfest 2021 ?

Yes

**Pull request merged**
